{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# The objective of this notebook is to extract features from the\n",
    "# information source 3, which are the 3D models step files located\n",
    "# in the local repository devis_path='C:/Users/BS/cpstdata/devis', and to store\n",
    "# those features as npz files in a directory called\n",
    "# step_path='C:/Users/BS/cpstdata/step_data'. \n",
    "\n",
    "# More details to be found under project proposal notebook relevant section."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importing necessary libraries\n",
    "import pandas as pd\n",
    "pd.set_option('display.max_columns', 150)\n",
    "pd.set_option('display.max_rows', 150)\n",
    "import numpy as np\n",
    "import sys\n",
    "import glob\n",
    "\n",
    "# Additional libraries specific to functions are imported at function definition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Creating variable for path name to the extracted data\n",
    "step_path='C:/Users/BS/cpstdata/step_data'\n",
    "\n",
    "# Store this variable for usage in other notebooks\n",
    "%store step_path\n",
    "\n",
    "#Getting stored data back from original notebooks where data is generated\n",
    "%store -r devis_path\n",
    "%store -r cpst_path\n",
    "\n",
    "#Checking the variables acctive in the notebook\n",
    "%whos"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setting up for utilisation of the CAD software FreeCAD\n",
    "\n",
    "# Importing FreeCAD\n",
    "import freecad\n",
    "import FreeCAD\n",
    "import FreeCADGui\n",
    "import Part, math\n",
    "from FreeCAD import Base\n",
    "\n",
    "# Setting path\n",
    "import sys, os\n",
    "import PyQt5\n",
    "%gui qt5\n",
    "os.environ[\"QT_API\"] = \"pyside\"\n",
    "prefix = os.environ['CONDA_PREFIX']\n",
    "sys.path.append(prefix+\"/\")\n",
    "sys.path.append(prefix+\"lib/\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Display of the version of FreeCAD used\n",
    "FreeCAD.Version()\n",
    "\n",
    "# Activate the GUI (Not used)\n",
    "#FreeCADGui.showMainWindow()\n",
    "\n",
    "# Clear the GUI selection (Not used)\n",
    "#thread_func(5)\n",
    "#Gui.Selection.clearSelection()\n",
    "#Gui.getMainWindow().deleteLater()\n",
    "#FreeCADGui.updateGui()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Context manager for reditrecting stdout/err to files\n",
    "\n",
    "class redirect_output(object):\n",
    "    \"\"\"context manager for reditrecting stdout/err to files\"\"\"\n",
    "\n",
    "\n",
    "    def __init__(self, stdout='', stderr=''):\n",
    "        self.stdout = stdout\n",
    "        self.stderr = stderr\n",
    "\n",
    "    def __enter__(self):\n",
    "        self.sys_stdout = sys.stdout\n",
    "        self.sys_stderr = sys.stderr\n",
    "\n",
    "        if self.stdout:\n",
    "            sys.stdout = open(self.stdout, 'w')\n",
    "        if self.stderr:\n",
    "            if self.stderr == self.stdout:\n",
    "                sys.stderr = sys.stdout\n",
    "            else:\n",
    "                sys.stderr = open(self.stderr, 'w')\n",
    "\n",
    "    def __exit__(self, exc_type, exc_value, traceback):\n",
    "        sys.stdout = self.sys_stdout\n",
    "        sys.stderr = self.sys_stderr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to import a file in FreeCAD and store its name\n",
    "\n",
    "def load_step(step_file):\n",
    "    print(step_file)\n",
    "    FreeCAD.loadFile(step_file)\n",
    "    # store file name\n",
    "    variables_dict['step_file']=str(step_file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to select all objects of the active document, print names and labels\n",
    "def objects_check():\n",
    "    \n",
    "    # store count of objects\n",
    "    variables_dict['objects_count']=len(FreeCAD.ActiveDocument.Objects)\n",
    "    \n",
    "    return FreeCAD.ActiveDocument.Objects\n",
    "\n",
    "#    # Display object label and name\n",
    "#    for obj in FreeCAD.ActiveDocument.Objects:\n",
    "#        print('Object Label: ',obj.Label)\n",
    "#        print('Object Name: ',obj.Name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to select active object in the active document and store\n",
    "# object label, name, haschilds\n",
    "\n",
    "def object_check(obj):\n",
    "    \n",
    "    # store active object Label\n",
    "    variables_dict['objects_label']=obj.Label\n",
    "\n",
    "    # store active object Name   \n",
    "    variables_dict['objects_fullname']=obj.FullName\n",
    "    \n",
    "    # store child check   \n",
    "    variables_dict['objects_haschild']=obj.hasChildElement() \n",
    "\n",
    "#return FreeCAD.ActiveDocument.ActiveObject\n",
    "# select the object and display selection in the GUI\n",
    "#obj = App.ActiveDocument.getObject(obj.Name)\n",
    "#Gui.Selection.addSelection(obj)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to store structural information relativ to object shape\n",
    "\n",
    "def object_features(obj):\n",
    "\n",
    "    variables_dict['objects_childshapes_count']=\\\n",
    "                                len(obj.Shape.childShapes())\n",
    "    \n",
    "    variables_dict['objects_compounds']=\\\n",
    "                                len(obj.Shape.removeSplitter().Compounds)\n",
    "    \n",
    "    variables_dict['objects_lenght']=\\\n",
    "                                obj.Shape.removeSplitter().Length\n",
    "    \n",
    "    variables_dict['objects_ShapeType']=\\\n",
    "                                obj.Shape.removeSplitter().ShapeType\n",
    "    \n",
    "    variables_dict['objects_count_shells']=\\\n",
    "                                len(obj.Shape.removeSplitter().Shells)\n",
    "    \n",
    "    variables_dict['objects_count_solids']=\\\n",
    "                                len(obj.Shape.removeSplitter().Solids)\n",
    "    \n",
    "    variables_dict['objects_count_subshapes']=\\\n",
    "                                len(obj.Shape.removeSplitter().SubShapes)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to retrieve the edges information with freeCAD\n",
    "\n",
    "def edges_retrieve(shape):\n",
    "\n",
    "    lenghts=[]\n",
    "    curves=[]\n",
    "    for edge in shape.Edges:\n",
    "        lenght=edge.Length\n",
    "        try:\n",
    "            curve=edge.Curve\n",
    "        except TypeError:\n",
    "            curve='undefined curve type'\n",
    "        lenghts.append(lenght)\n",
    "        curves.append(curve)\n",
    "\n",
    "    # Create a dataframe with all the edges parameters\n",
    "\n",
    "    df=pd.DataFrame([lenghts, curves], index=['lenght','curve']).T\n",
    "    df['curve']=df['curve'].astype(str)\n",
    "    df['lenght']=df['lenght'].astype(float)\n",
    "    df['curve']=df['curve'].str.extract(r'(?:^|(?:[.!?]\\s)|<)(\\w+)')\n",
    "    df_g=df.groupby('curve')\n",
    "    #df.head()\n",
    "\n",
    "    # Calculate features for the edges and store in the variables list\n",
    "\n",
    "    # - Count edges total\n",
    "    variables_dict['edges_count_total']=len(df)\n",
    "\n",
    "    # - Count edges per curve type\n",
    "    for i in df.curve.unique():\n",
    "        variables_dict['edges_count_{}'.format(i)]=df_g.count().loc[i,:].item()\n",
    "\n",
    "    # - Lenght per Curve types\n",
    "    for i in df.curve.unique():\n",
    "        variables_dict['edges_lenght_{}'.format(i)]=df_g.sum().loc[i,:].item()\n",
    "\n",
    "    # - Total lenght of edges\n",
    "    variables_dict['edges_lenght_total']=df.lenght.sum()\n",
    "\n",
    "    # - Lenght per Curve types / Total lenght of edges\n",
    "    for i in df.curve.unique():\n",
    "        variables_dict['edges_lenght_{}_to_total'.format(i)]\\\n",
    "            =df_g.sum().loc[i,:].item()/df.lenght.sum()\n",
    "\n",
    "    # - Describe Edges lenght values\n",
    "    for i in list(df.lenght.describe().index):\n",
    "        variables_dict['edges_lenght_{}'.format(i)]=\\\n",
    "                                        (df.lenght.describe()).loc[i].item()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to retrieve the faces with freeCAD\n",
    "\n",
    "def faces_retrieve(shape):\n",
    "\n",
    "    areas=[]\n",
    "    surfaces=[]\n",
    "    volumes=[]\n",
    "    volume_signs=[]\n",
    "    areplanar=[]\n",
    "    orientations_0=[]\n",
    "    orientations_1=[]\n",
    "    orientations_2=[]\n",
    "\n",
    "    for face in shape.Faces:\n",
    "        area=face.Area\n",
    "        surface=face.Surface\n",
    "        volume=face.Volume\n",
    "        if volume>0:\n",
    "            volume_sign=np.abs(volume)/volume\n",
    "        else:\n",
    "            volume_sign=1\n",
    "        isplanar=face.Surface.isPlanar()\n",
    "        try:\n",
    "            orientation_0=face.normalAt(0,0)[0]\n",
    "            orientation_1=face.normalAt(0,0)[1]\n",
    "            orientation_2=face.normalAt(0,0)[2]\n",
    "        except:\n",
    "            orientation_0=0\n",
    "            orientation_1=0\n",
    "            orientation_2=0\n",
    "\n",
    "        areas.append(area)\n",
    "        surfaces.append(surface)\n",
    "        volumes.append(np.abs(volume)) # We sum absolute value of faces volumes\n",
    "        volume_signs.append(volume_sign)\n",
    "        areplanar.append(isplanar)\n",
    "        orientations_0.append(orientation_0)\n",
    "        orientations_1.append(orientation_1)\n",
    "        orientations_2.append(orientation_2)\n",
    "\n",
    "    # Create a dataframe with all the faces parameters\n",
    "\n",
    "    df=pd.DataFrame([areas, surfaces, volumes, volume_signs,areplanar,\n",
    "                     orientations_0,orientations_1,orientations_2],\\\n",
    "                    index=['area','surface','volume','volume_sign','planar',\n",
    "                           'orientation_0', 'orientation_1', 'orientation_2']).T\n",
    "    df['surface']=df['surface'].astype(str)\n",
    "    df['orientation_0']=df['orientation_0'].astype(float)\n",
    "    df['orientation_1']=df['orientation_1'].astype(float)\n",
    "    df['orientation_2']=df['orientation_2'].astype(float)\n",
    "    df[['area','volume']]=df[['area','volume']].astype(float)\n",
    "    df['surface']=df['surface'].str.extract('(?:^|(?:[.!?]\\s)|<)(\\w+)')\n",
    "    df_g=df.groupby('surface')\n",
    "    #df.iloc[12:20,:]\n",
    "    #df_g.count()\n",
    "\n",
    "    # Retrieve unique faces orientations and corresponding total areas & counts\n",
    "\n",
    "    df_orient_g=df.round(decimals=4).groupby(['orientation_0',\n",
    "                                              'orientation_1',\n",
    "                                              'orientation_2'])\n",
    "    \n",
    "    df_orient_counts=df_orient_g.count().reset_index().area.rename('quantity')\n",
    "    \n",
    "    df_orient_axes=df_orient_g.count().reset_index()[['orientation_0',\n",
    "                                                      'orientation_1',\n",
    "                                                      'orientation_2']]\n",
    "    \n",
    "    df_orient_area=df_orient_g.sum().reset_index().area\n",
    "    \n",
    "    df_orient=pd.concat([df_orient_axes,df_orient_area,df_orient_counts],axis=1)\n",
    "    \n",
    "    # Calculate features for the faces and store in the variables list\n",
    "\n",
    "    # - Total area of shape\n",
    "    variables_dict['shape_area_total']=shape.Area\n",
    "\n",
    "    # - Total volume of shape\n",
    "    variables_dict['shape_volume_total']=np.abs(shape.Volume)\n",
    "\n",
    "    # - Total Count of faces\n",
    "    variables_dict['faces_count_total']=len(df)\n",
    "\n",
    "    # - Count faces per surface type\n",
    "    for i in df.surface.unique():\n",
    "        variables_dict['faces_count_{}'.format(i)]=\\\n",
    "                                            df_g.count().loc[i,'area'].item()\n",
    "\n",
    "    # - faces area per Surface types\n",
    "    for i in df.surface.unique():\n",
    "        variables_dict['faces_area_{}'.format(i)]=\\\n",
    "                                            df_g.sum().loc[i,'area'].item()\n",
    "\n",
    "    # - Total area of faces\n",
    "    variables_dict['faces_area_total']=df.area.sum()\n",
    "\n",
    "    # - Total volume of faces (a non-planar surface as a non-nul volume)\n",
    "    variables_dict['faces_volume_total']=df.volume.sum()\n",
    "\n",
    "    # - Area per surface types / Total area of faces\n",
    "    for i in df.surface.unique():\n",
    "        variables_dict['faces_area_{}_to_total'.format(i)]\\\n",
    "            =df_g.sum().loc[i,'area'].item()/df.area.sum()\n",
    "\n",
    "    # - Volume per surface types / Total volume of faces\n",
    "    for i in df.surface.unique():\n",
    "        variables_dict['faces_volume_{}_to_total'.format(i)]\\\n",
    "            =df_g.sum().loc[i,'volume'].item()/df.volume.sum()\n",
    "\n",
    "    # - Describe faces area values\n",
    "    for i in list(df.area.describe().index):\n",
    "        variables_dict['faces_area_{}'.format(i)]=\\\n",
    "                                (df.area.describe()).loc[i].item()\n",
    "\n",
    "    # - Describe faces orientations values\n",
    "    for i in list(df_orient.describe().index):\n",
    "        variables_dict['faces_orient_area_{}'.format(i)]=\\\n",
    "                                (df_orient.area.describe()).loc[i].item()\n",
    "        variables_dict['faces_orient_quantity_{}'.format(i)]=\\\n",
    "                                (df_orient.quantity.describe()).loc[i].item()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to retrieve the volumes and standard bounding box information\n",
    "\n",
    "def volumes_retrieve(shape):\n",
    "\n",
    "    # - bounding box X\n",
    "    X=shape.BoundBox.XLength\n",
    "    variables_dict['boundbox_X']=X\n",
    "\n",
    "    # - bounding box Y\n",
    "    Y=shape.BoundBox.YLength\n",
    "    variables_dict['boundbox_Y']=Y\n",
    "\n",
    "    # - bounding box Z\n",
    "    Z=shape.BoundBox.ZLength\n",
    "    variables_dict['boundbox_Z']=Z\n",
    "\n",
    "    # - Volume of the part\n",
    "    Volume_part=np.abs(shape.Volume)\n",
    "    variables_dict['volume_part']=Volume_part\n",
    "\n",
    "    # - Volume of the bounding box\n",
    "    Volume_box=X*Y*Z\n",
    "    variables_dict['volume_boundbox']=Volume_box\n",
    "\n",
    "    # - Volume of the part / Volume of the bounding box\n",
    "    variables_dict['volume_ratio_part_to_boundbox']=Volume_part/Volume_box\n",
    "\n",
    "    # - bounding box diag\n",
    "    variables_dict['boundbox_diagonal']=shape.BoundBox.DiagonalLength\n",
    "\n",
    "    # - Polynomial features of X,Y,Z\n",
    "\n",
    "    variables_dict['boundbox_X2']=X**2\n",
    "    variables_dict['boundbox_X3']=X**3\n",
    "    variables_dict['boundbox_Y2']=Y**2\n",
    "    variables_dict['boundbox_Y3']=Y**3\n",
    "    variables_dict['boundbox_Z2']=Z**2\n",
    "    variables_dict['boundbox_Z3']=Z**3\n",
    "    variables_dict['boundbox_XYZ']=X*Y*Z\n",
    "    variables_dict['boundbox_X2Y']=X**2*Y\n",
    "    variables_dict['boundbox_X2Z']=X**2*Z\n",
    "    variables_dict['boundbox_XY2']=X*Y**2\n",
    "    variables_dict['boundbox_Y2Z']=Y**2*Z\n",
    "    variables_dict['boundbox_XZ2']=X*Z**2\n",
    "    variables_dict['boundbox_YZ2']=Y*Z**2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Supporting definitions for the holes_retrieve() function\n",
    "\n",
    "#  Copyright 2020 Ulrich Brammer <ulrich@Pauline>\n",
    "#  \n",
    "#  This program is free software; you can redistribute it and/or modify\n",
    "#  it under the terms of the GNU General Public License as published by\n",
    "#  the Free Software Foundation; either version 2 of the License, or\n",
    "#  (at your option) any later version.\n",
    "#  \n",
    "#  This program is distributed in the hope that it will be useful,\n",
    "#  but WITHOUT ANY WARRANTY; without even the implied warranty of\n",
    "#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n",
    "#  GNU General Public License for more details.\n",
    "#  \n",
    "#  You should have received a copy of the GNU General Public License\n",
    "#  along with this program; if not, write to the Free Software\n",
    "#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,\n",
    "#  MA 02110-1301, USA.\n",
    "\n",
    "''' To do:\n",
    "Use this code to do a hole search.\n",
    "\n",
    "actual state, growTree is the selected analyzing mechanism to build \n",
    "a tree of face nodes with characteristic data.\n",
    "\n",
    "The tree is then analyzed to identify the type of the holes.\n",
    "  \n",
    "Analyzing faces step for detection of connected holes: \n",
    "- Search for largest face and start from it. \n",
    "- analyze first inner wires of a face, than outerwire.\n",
    "- Stop after detection of a cylinder with a parent cylinder.\n",
    "- Do not change side of part at through holes.\n",
    "  \n",
    "This strategy should detect first all holes on one side, \n",
    "than move to other sides. The second analyzing path can be ommitted.\n",
    "  \n",
    "'''\n",
    "\n",
    "import Part, math\n",
    "from FreeCAD import Base\n",
    "#import DraftVecUtils\n",
    "\n",
    "def equal_vertex(vert1, vert2, p=5):\n",
    "    # compares two vertices\n",
    "    return (round(vert1.X - vert2.X,p)==0 and round(vert1.Y - vert2.Y,p)==0 and round(vert1.Z - vert2.Z,p)==0)\n",
    "\n",
    "def equal_vector(vec1, vec2, p=5):\n",
    "    # compares two vectors\n",
    "    return (round(vec1.x - vec2.x,p)==0 and round(vec1.y - vec2.y,p)==0 and round(vec1.z - vec2.z,p)==0)\n",
    "\n",
    "def radial_vector(point, axis_pnt, axis):\n",
    "    chord = axis_pnt.sub(point)\n",
    "    norm = axis.cross(chord)\n",
    "    perp = axis.cross(norm)\n",
    "    # FreeCAD.Console.PrintLog( str(chord) + ' ' + str(norm) + ' ' + str(perp)+'\\n')\n",
    "    # print ( str(chord) + ' ' + str(norm) + ' ' + str(perp)+'\\n')\n",
    "    #test_line = Part.makeLine(axis_pnt.add(dist_rv),axis_pnt)\n",
    "    # test_line = Part.makeLine(axis_pnt.add(perp),axis_pnt)\n",
    "    # test_line = Part.makeLine(point, axis_pnt)\n",
    "    # Part.show(test_line)\n",
    "    return perp.normalize()\n",
    "\n",
    "def cone_norm(point, apex, axis):\n",
    "    chord = apex.sub(point)\n",
    "    #norm = axis.cross(chord)\n",
    "    rad = radial_vector(point, apex, axis)\n",
    "    norm = rad.cross(chord)\n",
    "    perp = chord.cross(norm)\n",
    "    # FreeCAD.Console.PrintLog( str(chord) + ' ' + str(norm) + ' ' + str(perp)+'\\n')\n",
    "    # print ( str(chord) + ' ' + str(norm) + ' ' + str(perp)+'\\n')\n",
    "    test_line = Part.makeLine(point.add(perp),point)\n",
    "    # test_line = Part.makeLine(point, axis_pnt)\n",
    "    #Part.show(test_line, 'ConeNormal')\n",
    "    return perp.normalize()\n",
    "\n",
    "\n",
    "def cone_test(point, apex, axis, testVec, p=5):\n",
    "    chord = apex.sub(point)\n",
    "    norm = axis.cross(chord)\n",
    "    #rad = radial_vector(point, apex, axis)\n",
    "    #norm = rad.cross(chord)\n",
    "    perp = chord.cross(norm)\n",
    "    # FreeCAD.Console.PrintLog( str(chord) + ' ' + str(norm) + ' ' + str(perp)+'\\n')\n",
    "    # print ( str(chord) + ' ' + str(norm) + ' ' + str(perp)+'\\n')\n",
    "    test_line = Part.makeLine(point.add(perp),point)\n",
    "    # test_line = Part.makeLine(point, axis_pnt)\n",
    "    #Part.show(test_line, 'ConeTestNormal')\n",
    "    result = testVec - perp.normalize()\n",
    "    #print 'cone test result: ', result,\n",
    "    #print 'cone NormVec ', testVec, ' test ', perp.normalize()\n",
    "    return (round(result.x,p)==0 and round(result.y,p)==0 and round(result.z,p)==0)\n",
    "\n",
    "\n",
    "\n",
    "class FaceTree(object):\n",
    "  ''' This class defines the nodes of a tree. The tree is constructed by\n",
    "  the functions growTree of the ShapeAna class.\n",
    "  Each face of the part gets a node in the tree.\n",
    "  The indexes are the number of the face in the original part.\n",
    "  '''\n",
    "  def __init__(self, unfoldShape = None, f_idx=None, Parent_node= None, Parent_edge = None, pWire = None):\n",
    "    ''' unfoldShape is the Shape to be analyzed.\n",
    "    '''\n",
    "    self.NoStopFace = True # The analysis should only stop at a StopFace\n",
    "    self.bore = False # True in case the face represents a round hole or pocket.\n",
    "    if unfoldShape is not None: # fix me a shape is needed to unfold\n",
    "        theFace = unfoldShape.Faces[f_idx]\n",
    "    #else: #additions#print ('need a shape to unfold! Select one first!')\n",
    "    self.idx = f_idx  # index of the face\n",
    "    F_type = str(theFace.Surface)\n",
    "    #print ('analyzing Face'+str(f_idx+1), ' ', F_type)\n",
    "    \n",
    "    self.node_type = None  # 'Flat' or 'Cylinder' or 'Cone', see below\n",
    "    self.p_node = Parent_node   # Parent node\n",
    "    self.p_edge = Parent_edge # the connecting edge to the parent node\n",
    "    self.child_list = [] # List of child-nodes = link to tree structure\n",
    "    self.child_idx_list = [] # List of child_idx\n",
    "    # need also a list of indices of child faces\n",
    "    self.normal = None # normal of the face, used to calculate the rotation, calculated below\n",
    "    self.minusTan = None # flag to correct the self.secondRotAngle, Needed anymore?\n",
    "    \n",
    "    if Parent_node is None:\n",
    "        self.rotCenter = None # A point on the edge, needed for further calculations\n",
    "    else:\n",
    "      curveType = str(self.p_edge.Curve)\n",
    "      if \"<Line\" in curveType:\n",
    "        edgeParameter = self.p_edge.FirstParameter\n",
    "      else:\n",
    "        edgeParameter = (self.p_edge.FirstParameter + self.p_edge.LastParameter) / 2.0\n",
    "\n",
    "      self.rotCenter = self.p_edge.valueAt(edgeParameter) # A point on the edge, needed for further calculations\n",
    "    \n",
    "    self.cAxis = None # Axis of a cylindrical or conical face\n",
    "    self.cCenter = None \n",
    "    self.radius = None # radius of a cylinder or whatever needs a radius.\n",
    "    self.analysis_ok = True # indicator if something went wrong with the analysis of the face\n",
    "    self.error_code = None # index to unfold_error dictionary\n",
    "    \n",
    "    s_Ori = theFace.Orientation\n",
    "\n",
    "\n",
    "    F_type = str(theFace.Surface)\n",
    "    if F_type == \"<Plane object>\":\n",
    "      self.node_type = 'Flat' # fixme\n",
    "      #FreeCAD.Console.PrintLog(\"Face\"+ str(f_idx+1) + \" Type: \"+ str(self.node_type) + \"\\n\")\n",
    "    \n",
    "      #s_Ori = theFace.Orientation\n",
    "      #s_Axis = theFace.Surface.Axis # is not reliable in all cases\n",
    "      s_Axis = theFace.Surface.normal(0.0,0.0)\n",
    "      if s_Ori == 'Forward':\n",
    "        self.normal = Base.Vector(s_Axis.x, s_Axis.y, s_Axis.z)\n",
    "      else:                    \n",
    "        self.normal = Base.Vector(-s_Axis.x, -s_Axis.y, -s_Axis.z)\n",
    "      #print ('Orientation: ', s_Ori, ' Type: ', str(self.node_type), ' normal ', self.normal)\n",
    "\n",
    "      #s_Posi = theFace.Surface.Position\n",
    "      s_Posi = theFace.Edges[0].Vertexes[0].Point\n",
    "      normal_line = Part.makeLine(s_Posi + self.normal, s_Posi)\n",
    "      #Part.show(normal_line, 'normal_line'+str(f_idx+1)+'_')\n",
    "      \n",
    "      # a flat face can be a \"StopFace\". This is the case for a \n",
    "      # through hole. The tree growing algorithm should not go\n",
    "      # through a through hole, to visit the next face.\n",
    "      # This is the case when the outer wire of the actual Face has \n",
    "      # vertexes different to the parent wire.\n",
    "      if Parent_node:\n",
    "        if Parent_node.bore:\n",
    "          #print ('child face of bore')\n",
    "          # pV=Parent_edge.Vertexes[0]\n",
    "          # fV = theFace.Wires[0].Vertexes[0]\n",
    "          # print (pV.X, ' ', pV.Y, ' ', pV.Z)\n",
    "          # print (fV.X, ' ', fV.Y, ' ', fV.Z)\n",
    "          # Part.show(Parent_edge)\n",
    "          # Part.show(theFace.Wires[0])\n",
    "          if not equal_vertex(Parent_edge.Vertexes[0], theFace.Wires[0].Vertexes[0]):\n",
    "            self.NoStopFace = False\n",
    "            #print (' edge type: ', theFace.Wires[0].Edges[0])\n",
    "            testEdge = theFace.Wires[0].Edges[0]\n",
    "            if hasattr(testEdge,\"Curve\"):\n",
    "              #print (theFace.Wires[0].Edges[0].__getattribute__('Curve'))\n",
    "              if 'Circle' in str(testEdge.__getattribute__('Curve')):\n",
    "                self.NoStopFace = True\n",
    "\n",
    "\n",
    "\n",
    "    if F_type == \"<Cylinder object>\":\n",
    "      self.node_type = 'Cylinder' \n",
    "      #FreeCAD.Console.PrintLog(\"Face\"+ str(f_idx+1) + \" Type: \"+ str(self.node_type) + \"\\n\")\n",
    "    \n",
    "      #s_Ori = self._Shape.Faces[f_idx].Orientation\n",
    "      s_Center = theFace.Surface.Center\n",
    "      self.cCenter = s_Center\n",
    "      self.radius = theFace.Surface.Radius\n",
    "      self.cAxis = theFace.Surface.Axis #fix me need to understand the minus sign?\n",
    "      if Parent_node is None:\n",
    "        angle_0 = theFace.ParameterRange[0]\n",
    "        length_0 = theFace.ParameterRange[2]\n",
    "        #s_Posi = theFace.Surface.value(angle_0, length_0)\n",
    "        #s_Posi = theFace.Edges[0].Vertexes[0]\n",
    "        self.rotCenter = theFace.Edges[0].Vertexes[0].Point\n",
    "        # self.axis = self.cAxis\n",
    "      else:\n",
    "        cylinderAngle = theFace.ParameterRange[1] - theFace.ParameterRange[0]\n",
    "        #print ('cylinder angle0: ', theFace.ParameterRange[0],\n",
    "        #       ' cylinder angle1: ', theFace.ParameterRange[1],\n",
    "        if cylinderAngle > (2*math.pi - 0.01):\n",
    "          self.bore = True\n",
    "          print ( 'D: ', 2*self.radius, ' L: ', abs(theFace.ParameterRange[2]-theFace.ParameterRange[3]), \n",
    "                 ' Axis: ', self.cAxis, ' center: ', s_Center)\n",
    "          holes.append((2*self.radius,abs(theFace.ParameterRange[2]-theFace.ParameterRange[3])))\n",
    "          if Parent_node.bore:\n",
    "            print('attached 90° to above bore!')\n",
    "          if Parent_node.p_node:\n",
    "            if Parent_node.p_node.bore:\n",
    "              print('Part of countersunk bore!')\n",
    "\n",
    "      #self.normal = radial_vector(self.rotCenter, s_Center, self.cAxis)\n",
    "      #need to check the direction of the cylinder axis\n",
    "      self.u0, self.v0 = theFace.Surface.parameter(self.rotCenter)\n",
    "      s_Axis = theFace.Surface.normal(self.u0, self.v0)\n",
    "      if s_Ori == 'Forward':\n",
    "        self.normal = Base.Vector(s_Axis.x, s_Axis.y, s_Axis.z)\n",
    "      else:                    \n",
    "        self.normal = Base.Vector(-s_Axis.x, -s_Axis.y, -s_Axis.z)\n",
    "      \n",
    "      uTest = self.u0 + 0.1\n",
    "      testPnt = theFace.Surface.value(uTest, self.v0)\n",
    "      tripleProd = self.normal.cross(self.cAxis).dot(testPnt-self.rotCenter)\n",
    "      #print 'tripleProd: ', tripleProd\n",
    "      self.tanVec = self.normal.cross(self.cAxis)\n",
    "      if tripleProd < 0:\n",
    "        #self.cAxis = -self.cAxis\n",
    "        self.tanVec = self.tanVec.multiply(-1.0) #self.normal.cross(self.cAxis)\n",
    "        self.minusTan = True\n",
    "        \n",
    "      #axis_line = Part.makeLine(self.rotCenter + self.normal, self.rotCenter)\n",
    "      #Part.show(axis_line, 'normal_line'+str(f_idx+1)+'_')\n",
    "\n",
    "    if F_type == \"<Cone object>\":\n",
    "      self.node_type = 'Cone' # \n",
    "      FreeCAD.Console.PrintLog(\"Face\"+ str(f_idx+1) + \" Type: \"+ str(self.node_type) + \"\\n\")\n",
    "      \n",
    "      #s_Ori = self._Shape.Faces[f_idx].Orientation\n",
    "      s_Center = theFace.Surface.Center\n",
    "      self.cCenter = s_Center\n",
    "      self.apex = theFace.Surface.Apex\n",
    "      self.semiAngle = theFace.Surface.SemiAngle\n",
    "      #self.radius = theFace.Surface.Radius\n",
    "      self.cAxis = theFace.Surface.Axis #fix me need to understand the minus sign?\n",
    "      if Parent_node is None:\n",
    "        #search for an edge that is not a circle, because it could be the apex\n",
    "        for edge in theFace.OuterWire.Edges:\n",
    "          eType = str(edge.Curve)\n",
    "          if not (\"Circle\" in eType):\n",
    "            coneEdge = edge\n",
    "            break\n",
    "        self.rotCenter = coneEdge.Vertexes[0].Point\n",
    "        self.axis = self.cAxis\n",
    "        # test if self.rotCenter is identical with self.apex\n",
    "        if equal_vector(self.rotCenter, self.apex):\n",
    "          #self.p_edge.FirstParameter\n",
    "          self.rotCenter = coneEdge.Vertexes[1].Point\n",
    "      else:\n",
    "        if equal_vector(self.rotCenter, self.apex):\n",
    "          #self.p_edge.FirstParameter\n",
    "          self.rotCenter = self.p_edge.valueAt(self.p_edge.LastParameter)\n",
    "          self.axis = self.p_edge.tangentAt(self.p_edge.LastParameter) # the rotation axis\n",
    "      #self.normal = radial_vector(self.rotCenter, s_Center, self.cAxis)\n",
    "      self.normal = cone_norm(self.rotCenter, self.apex, self.cAxis)\n",
    "      if cone_test(self.rotCenter, self.apex, self.cAxis, self.normal):\n",
    "        #additions#print ('cone test True')\n",
    "        self.reversCone = True\n",
    "      else:\n",
    "        #additions#print ('cone test False')\n",
    "        self.reversCone = False\n",
    "      #need to check the direction of the cylinder axis\n",
    "      self.u0, self.v0 = theFace.Surface.parameter(self.rotCenter)\n",
    "      uTest = self.u0 + 0.1\n",
    "      testPnt = theFace.Surface.value(uTest, self.v0)\n",
    "      tripleProd = self.normal.cross(self.cAxis).dot(testPnt-self.rotCenter)\n",
    "      #additions#print ('cone tripleProd: ', tripleProd)\n",
    "      #self.tanVec = self.normal.cross(self.cAxis)\n",
    "      if tripleProd < 0:\n",
    "        #self.tanVec = -self.tanVec #self.normal.cross(self.cAxis)\n",
    "        self.minusTan = True\n",
    "      self.v0 = (self.cCenter-self.apex).Length / math.cos(self.semiAngle)\n",
    "\n",
    "\n",
    "\n",
    "  def get_Face_idx(self):\n",
    "    # get the face index from the tree-element\n",
    "    return self.idx\n",
    "\n",
    "class ShapeAna(object):\n",
    "  ''' This class builds the FaceTree with all information in its nodes.\n",
    "  It does a shape analysis by iterative visiting of all faces of the shape.\n",
    "  It does not work for shapes having inner faces not connected to the \n",
    "  outer faces.\n",
    "  The algorithm is tuned to detect round holes in flat objects.\n",
    "  \n",
    "  '''\n",
    "\n",
    "  def __init__(self):\n",
    "    self.root = None # getObject adds the root node if parent_node == None\n",
    "    self._Shape = None\n",
    "\n",
    "    self.error_code = None\n",
    "    self.failed_face_idx = None\n",
    "    self.f_list = [] # list with all faces of the object\n",
    "    self.idx_list = [] # list with the face indexes\n",
    "    \n",
    "\n",
    "  def getObject(self, TheShape, f_idx):\n",
    "    self._Shape = TheShape.copy()\n",
    "\n",
    "    if not self._Shape.isValid():\n",
    "      FreeCAD.Console.PrintLog(\"The shape is not valid!\" + \"\\n\")\n",
    "      self.error_code = 4  # Starting: invalid shape\n",
    "      self.failed_face_idx = f_idx\n",
    "\n",
    "    self.f_list = self._Shape.Faces[:] \n",
    "    self.idx_list = list(range(len (self._Shape.Faces)))\n",
    "\n",
    "\n",
    "  def growTree(self, f_idx = 0, parent_node = None, parent_edge = None, pWire = None): \n",
    "    #take a face\n",
    "    # analyze the face and create a node object of class FaceTree.\n",
    "    tNode = FaceTree(self._Shape, f_idx, parent_node, parent_edge, pWire)\n",
    "    if tNode.NoStopFace:\n",
    "      # This face should be a node in the tree, and is therefore known!\n",
    "      # removed from the list of all not visited faces\n",
    "      self.idx_list.remove(f_idx)\n",
    "      # This means, it could also not be found as neighbor face anymore.\n",
    "  \n",
    "      if parent_node is None:\n",
    "        self.root = tNode\n",
    "      else:\n",
    "        #put the node of the face into the tree structure.\n",
    "        parent_node.child_list.append(tNode)\n",
    "        \n",
    "      #print ('idx_list: ', self.idx_list)\n",
    "      such_list = self.idx_list[:] \n",
    "  \n",
    "      if self.error_code is None: # go only further in case of no error.\n",
    "        edge_list = []\n",
    "        #print (self.f_list[f_idx].Area)\n",
    "        #print 'Face', f_idx+1, ' has ', len(self.f_list[f_idx].OuterWire.Edges), 'edges.'\n",
    "        # Each face has a list of wires.\n",
    "        # Analyze first the inner wires, than the outer wire.\n",
    "        # We therefore must rearrange the list of wires, because the outer\n",
    "        # wire is the first in the list.\n",
    "        wireList = list(range(len(self.f_list[f_idx].Wires)))\n",
    "        wireList.remove(0)\n",
    "        wireList.append(0)\n",
    "        #for fWire in self.f_list[f_idx].Wires:\n",
    "        for wIdx in wireList:\n",
    "          fWire = self.f_list[f_idx].Wires[wIdx]\n",
    "          for n_edge in fWire.Edges:\n",
    "                if parent_edge:\n",
    "                    if not parent_edge.isSame(n_edge):\n",
    "                        edge_list.append(n_edge)\n",
    "                else:\n",
    "                    edge_list.append(n_edge)\n",
    "          #print 'edge_list edges: ', len(edge_list)\n",
    "    \n",
    "          #für jede Kante:\n",
    "          for sEdge in edge_list:\n",
    "            #suche die angrenzende Fläche.\n",
    "            the_index = None\n",
    "            for i in self.idx_list:\n",
    "              for sf_edge in self.f_list[i].Edges:\n",
    "                if sf_edge.isSame(sEdge):\n",
    "                    the_index = i\n",
    "                    #print 'got edge face: Face', str(i+1)\n",
    "                    break\n",
    "              if the_index is not None:\n",
    "                #Baumzweig(angrenzende Fläche)\n",
    "                self.growTree(the_index, tNode, sEdge, fWire)\n",
    "                break\n",
    "            #print 'got face index: ', the_index"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to retrieve holes parameters\n",
    "\n",
    "def holes_retrieve(shape):\n",
    "    print ('Starting with face1')\n",
    "    theFace = 0\n",
    "    #s = Gui.Selection.getSelection()\n",
    "    #s = FreeCAD.ActiveDocument.ActiveObject\n",
    "\n",
    "    theUnfold = ShapeAna()\n",
    "    theUnfold.getObject(shape, theFace)#s[0]\n",
    "    theUnfold.growTree(theFace, None, None)\n",
    "\n",
    "    FreeCAD.Console.PrintLog('Analyse beendet' + \"\\n\")\n",
    "\n",
    "    # List of the holes identified\n",
    "    print(holes)\n",
    "\n",
    "    # - Number of holes\n",
    "    variables_dict['holes_count']=len(holes)\n",
    "    \n",
    "    if len(holes)>0:\n",
    "    \n",
    "        # - Number of different holes diameters\n",
    "        variables_dict['holes_diameters_count']=\\\n",
    "                                    len(np.unique([i[0] for i in holes]))\n",
    "\n",
    "        # - Diameters: mini maxi average std\n",
    "        variables_dict['holes_diameter_min']=min([i[0] for i in holes])\n",
    "        variables_dict['holes_diameter_max']=max([i[0] for i in holes])\n",
    "        variables_dict['holes_diameter_avg']=np.mean([i[0] for i in holes])\n",
    "        variables_dict['holes_diameter_std']=np.std([i[0] for i in holes])\n",
    "\n",
    "        # - Volume of drillings\n",
    "        variables_dict['holes_volume_min']=\\\n",
    "                                min([i[1]*np.pi*(i[0]/2)**2 for i in holes])\n",
    "        variables_dict['holes_volume_max']=\\\n",
    "                                max([i[1]*np.pi*(i[0]/2)**2 for i in holes])\n",
    "        variables_dict['holes_volume_avg']=\\\n",
    "                                np.mean([i[1]*np.pi*(i[0]/2)**2 for i in holes])\n",
    "        variables_dict['holes_volume_std']=\\\n",
    "                                np.std([i[1]*np.pi*(i[0]/2)**2 for i in holes])\n",
    "    else:\n",
    "        variables_dict['holes_diameters_count']=np.nan\n",
    "        variables_dict['holes_diameter_min']=np.nan\n",
    "        variables_dict['holes_diameter_max']=np.nan\n",
    "        variables_dict['holes_diameter_avg']=np.nan\n",
    "        variables_dict['holes_diameter_std']=np.nan\n",
    "        variables_dict['holes_volume_min']=np.nan\n",
    "        variables_dict['holes_volume_max']=np.nan\n",
    "        variables_dict['holes_volume_avg']=np.nan\n",
    "        variables_dict['holes_volume_std']=np.nan\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Supporting definitions for the box_retrieve() function\n",
    "# adapted from: http://jamesgregson.blogspot.com/2011/03/latex-test.html\n",
    "\n",
    "from numpy import ndarray, array, asarray, dot, cross, cov,\n",
    "from numpy import array, finfo, min as npmin, max as npmax\n",
    "\n",
    "from numpy.linalg import eigh, norm\n",
    "\n",
    "class OBB:\n",
    "    def __init__(self):\n",
    "        self.rotation = None\n",
    "        self.min = None\n",
    "        self.max = None\n",
    "\n",
    "    def transform(self, point):\n",
    "        return dot(array(point), self.rotation)\n",
    "\n",
    "    @property\n",
    "    def centroid(self):\n",
    "        return self.transform((self.min + self.max) / 2.0)\n",
    "\n",
    "    @property\n",
    "    def extents(self):\n",
    "        return abs(self.transform((self.max - self.min) / 2.0))\n",
    "\n",
    "    @property\n",
    "    def points(self):\n",
    "        return [\n",
    "            # upper cap: ccw order in a right-hand system\n",
    "            # rightmost, topmost, farthest\n",
    "            self.transform((self.max[0], self.max[1], self.min[2])),\n",
    "            # leftmost, topmost, farthest\n",
    "            self.transform((self.min[0], self.max[1], self.min[2])),\n",
    "            # leftmost, topmost, closest\n",
    "            self.transform((self.min[0], self.max[1], self.max[2])),\n",
    "            # rightmost, topmost, closest\n",
    "            self.transform(self.max),\n",
    "            # lower cap: cw order in a right-hand system\n",
    "            # leftmost, bottommost, farthest\n",
    "            self.transform(self.min),\n",
    "            # rightmost, bottommost, farthest\n",
    "            self.transform((self.max[0], self.min[1], self.min[2])),\n",
    "            # rightmost, bottommost, closest\n",
    "            self.transform((self.max[0], self.min[1], self.max[2])),\n",
    "            # leftmost, bottommost, closest\n",
    "            self.transform((self.min[0], self.min[1], self.max[2])),\n",
    "        ]\n",
    "\n",
    "    @classmethod\n",
    "    def build_from_covariance_matrix(cls, covariance_matrix, points):\n",
    "        if not isinstance(points, ndarray):\n",
    "            points = array(points, dtype=float)\n",
    "        assert points.shape[1] == 3\n",
    "\n",
    "        obb = OBB()\n",
    "\n",
    "        _, eigen_vectors = eigh(covariance_matrix)\n",
    "\n",
    "        def try_to_normalize(v):\n",
    "            n = norm(v)\n",
    "            if n < finfo(float).resolution:\n",
    "                raise ZeroDivisionError\n",
    "            return v / n\n",
    "\n",
    "        r = try_to_normalize(eigen_vectors[:, 0])\n",
    "        u = try_to_normalize(eigen_vectors[:, 1])\n",
    "        f = try_to_normalize(eigen_vectors[:, 2])\n",
    "\n",
    "        obb.rotation = array((r, u, f)).T\n",
    "\n",
    "        # apply the rotation to all the position vectors of the array\n",
    "        # TODO : this operation could be vectorized with tensordot\n",
    "        p_primes = asarray([obb.rotation.dot(p) for p in points])\n",
    "        obb.min = npmin(p_primes, axis=0)\n",
    "        obb.max = npmax(p_primes, axis=0)\n",
    "\n",
    "        return obb\n",
    "\n",
    "    @classmethod\n",
    "    def build_from_triangles(cls, points, triangles):\n",
    "        for point in points:\n",
    "            if len(point) != 3:\n",
    "                raise Exception('points have to have 3-elements')\n",
    "\n",
    "        weighed_mean = array([0, 0, 0], dtype=float)\n",
    "        area_sum = 0\n",
    "        c00 = c01 = c02 = c11 = c12 = c22 = 0\n",
    "        for i in range(0, len(triangles), 3):\n",
    "            p = array(points[triangles[i]], dtype=float)\n",
    "            q = array(points[triangles[i + 1]], dtype=float)\n",
    "            r = array(points[triangles[i + 2]], dtype=float)\n",
    "            mean = (p + q + r) / 3.0\n",
    "            area = norm(cross((q - p), (r - p))) / 2.0\n",
    "            weighed_mean += mean * area\n",
    "            area_sum += area\n",
    "            c00 += (9.0 * mean[0] * mean[0] + p[0] * p[0] + q[0] * q[0] + r[0] * r[0]) * (area / 12.0)\n",
    "            c01 += (9.0 * mean[0] * mean[1] + p[0] * p[1] + q[0] * q[1] + r[0] * r[1]) * (area / 12.0)\n",
    "            c02 += (9.0 * mean[0] * mean[2] + p[0] * p[2] + q[0] * q[2] + r[0] * r[2]) * (area / 12.0)\n",
    "            c11 += (9.0 * mean[1] * mean[1] + p[1] * p[1] + q[1] * q[1] + r[1] * r[1]) * (area / 12.0)\n",
    "            c12 += (9.0 * mean[1] * mean[2] + p[1] * p[2] + q[1] * q[2] + r[1] * r[2]) * (area / 12.0)\n",
    "\n",
    "        weighed_mean /= area_sum\n",
    "        c00 /= area_sum\n",
    "        c01 /= area_sum\n",
    "        c02 /= area_sum\n",
    "        c11 /= area_sum\n",
    "        c12 /= area_sum\n",
    "        c22 /= area_sum\n",
    "\n",
    "        c00 -= weighed_mean[0] * weighed_mean[0]\n",
    "        c01 -= weighed_mean[0] * weighed_mean[1]\n",
    "        c02 -= weighed_mean[0] * weighed_mean[2]\n",
    "        c11 -= weighed_mean[1] * weighed_mean[1]\n",
    "        c12 -= weighed_mean[1] * weighed_mean[2]\n",
    "        c22 -= weighed_mean[2] * weighed_mean[2]\n",
    "\n",
    "        covariance_matrix = ndarray(shape=(3, 3), dtype=float)\n",
    "        covariance_matrix[0, 0] = c00\n",
    "        covariance_matrix[0, 1] = c01\n",
    "        covariance_matrix[0, 2] = c02\n",
    "        covariance_matrix[1, 0] = c01\n",
    "        covariance_matrix[1, 1] = c11\n",
    "        covariance_matrix[1, 2] = c12\n",
    "        covariance_matrix[2, 0] = c02\n",
    "        covariance_matrix[1, 2] = c12\n",
    "        covariance_matrix[2, 2] = c22\n",
    "\n",
    "        return OBB.build_from_covariance_matrix(covariance_matrix, points)\n",
    "\n",
    "    @classmethod\n",
    "    def build_from_points(cls, points):\n",
    "        if not isinstance(points, ndarray):\n",
    "            points = array(points, dtype=float)\n",
    "        assert points.shape[1] == 3, 'points have to have 3-elements'\n",
    "        # no need to store the covariance matrix\n",
    "        return OBB.build_from_covariance_matrix(cov(points, y=None,\n",
    "                                                    rowvar=0, bias=1), points)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to retrieve the optimal bounding box around the object,\n",
    "# with optimized orientation\n",
    "\n",
    "from scipy.spatial import ConvexHull\n",
    "import Points, Part\n",
    "import pyobb\n",
    "#import PointsGui\n",
    "#Gui.runCommand('Points_Convert')\n",
    "\n",
    "def box_retrieve(shape):\n",
    "    points=[v.Point for v in shape.Vertexes]\n",
    "    hull = ConvexHull(points,qhull_options=None)#'QJ'\n",
    "    faces = []\n",
    "    for i in hull.simplices:\n",
    "        wire = Part.makePolygon([FreeCAD.Vector(points[i[0]]),\n",
    "                                 FreeCAD.Vector(points[i[1]]),\n",
    "                                 FreeCAD.Vector(points[i[2]]),\n",
    "                                 FreeCAD.Vector(points[i[0]])])\n",
    "        faces.append(Part.Face(wire))\n",
    "\n",
    "    shell = Part.makeShell(faces)\n",
    "    Part.show(shell)\n",
    "\n",
    "    hullpts = [points[i] for i in hull.vertices]\n",
    "    obb = OBB.build_from_points(hullpts)\n",
    "\n",
    "    obbvec = [FreeCAD.Vector(p)for p in obb.points]\n",
    "\n",
    "    faces = []\n",
    "    idx   = [[0,1,2,3,0],[4,5,6,7,4],[0,1,4,5,0],\n",
    "             [2,3,6,7,2],[1,2,7,4,1],[0,5,6,3,0]]\n",
    "    for ix in idx:\n",
    "        wire = Part.makePolygon([obbvec[i] for i in ix])\n",
    "        faces.append(Part.Face(wire))\n",
    "\n",
    "    shell = Part.makeShell(faces)\n",
    "    doc = FreeCAD.ActiveDocument\n",
    "    obj = doc.addObject('Part::Feature', 'OBB')\n",
    "    obj.Shape = shell\n",
    "    #obj.ViewObject.ShapeColor = (1.00,0.67,0.00)\n",
    "    #obj.ViewObject.Transparency = 50\n",
    "\n",
    "    shell_1 = Part.makeShell(faces)\n",
    "    obj_1 = doc.addObject('Part::Feature', 'BBOX')\n",
    "    obj_1.Shape = shell_1\n",
    "    #obj_1.ViewObject.ShapeColor = (1.00,0.67,0.00)\n",
    "    #obj_1.ViewObject.Transparency = 50\n",
    "\n",
    "\n",
    "    # Volumes and bounding box / Optimized BOX\n",
    "\n",
    "    # - Volume of the optimized bounding box\n",
    "    Volume_box_opt=np.abs(obj.Shape.Volume)\n",
    "    variables_dict['boundbox_optimized_volume']=Volume_box_opt\n",
    "\n",
    "    # - Volume of the part / Volume of the bounding box\n",
    "    variables_dict['boundbox_optimized_volume_ratio']=\\\n",
    "                                variables_dict['volume_part']/Volume_box_opt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Defining a waiting time to allow the GUI to load the step file\n",
    "# Function is not used currently, as we are not using the GUI.\n",
    "\n",
    "import threading\n",
    "import time\n",
    "\n",
    "exit_flag = threading.Event()\n",
    "\n",
    "def thread_func(sec): \n",
    "    while not exit_flag.wait(timeout=sec):\n",
    "        print('{} have passed ... we continue'.format(sec))\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Identify the list of step files to be processed \n",
    "\n",
    "step_list=\\\n",
    "        glob.glob(devis_path+'/**/*.step', recursive=True) \\\n",
    "        +glob.glob(devis_path+'/**/*.stp', recursive=True)\n",
    "\n",
    "step_files=[i.replace('\\\\','/') for i in step_list]\n",
    "\n",
    "step_files[0:10]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to preprocess step files by batches\n",
    "\n",
    "def get_batch(step_files,size):\n",
    "    idx_shuff=np.arange(len(step_files))\n",
    "    #np.random.shuffle(idx_shuff)\n",
    "    for i in range(0,len(step_files),size):\n",
    "        idx_batch=idx_shuff[i:i+size]\n",
    "        yield [step_files[i] for i in idx_batch]\n",
    "\n",
    "for step_files_batch in get_batch(step_files, 3):\n",
    "    print(step_files_batch)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Starting iteration on the list of steps files to be processed\n",
    "\n",
    "# Working by batches of files\n",
    "batch_size=1\n",
    "batches=np.int(np.ceil(len(step_files)/batch_size))\n",
    "print('batch size: ',batch_size)\n",
    "print('batches: ',batches)\n",
    "skipped_batch=0\n",
    "\n",
    "for batch,step_files_batch in enumerate(get_batch(step_files, batch_size)):\n",
    "    \n",
    "    print('\\n\\nWorking on batch {} from {} ...'.format(batch+1,batches))\n",
    "    print('Files in batch: ',step_files_batch)\n",
    "    \n",
    "    with redirect_output(step_path+'/output_{}_from_{}.txt'\\\n",
    "                                                     .format(batch+1,batches)):\n",
    "        \n",
    "        # Initialize dataframe containing variables extracted from step files\n",
    "        df_features=pd.DataFrame()\n",
    "        \n",
    "        try:\n",
    "\n",
    "            for step_file in step_files_batch:\n",
    "\n",
    "                # Initialize a dictionary of variables to be extracted\n",
    "                print('\\n\\nInitialize dictionnary of variables ...')\n",
    "                variables_dict={}\n",
    "\n",
    "                # Load step file\n",
    "                print('Loading new step file.')\n",
    "                load_step(step_file)\n",
    "\n",
    "                # Get list of objects in step file\n",
    "                print('Get list of objects in step file...')\n",
    "                objects=objects_check()\n",
    "\n",
    "                # Iterate over the objects\n",
    "                print('Iterate over the objects...')\n",
    "                for obj in objects:\n",
    "\n",
    "                    print('Adressing next object...')\n",
    "                    obj_volume=obj.Shape.Volume\n",
    "                    print('object volume: ',obj_volume)\n",
    "\n",
    "                    # Store information about each object\n",
    "                    print('Store information about each object...')\n",
    "                    object_check(obj)\n",
    "\n",
    "                    # Store structural information relativ to object shape\n",
    "                    print('Store information relativ to object shape...')\n",
    "                    object_features(obj)\n",
    "\n",
    "                    # Get list of solids in object\n",
    "                    print('Get list of solids in object...')\n",
    "                    solids=obj.Shape.removeSplitter().Solids\n",
    "                    #if obj.hasChildElement(): solids=obj.Shape.childShapes()\n",
    "                    #else: solids=[obj.Shape]\n",
    "\n",
    "                    # Iterate over the solids\n",
    "                    print('Iterate over the solids...')\n",
    "                    for solid in solids:\n",
    "\n",
    "                        print('Adressing next solid...')\n",
    "\n",
    "                        try:\n",
    "                            # Refine shape to produces a non-parametric copy\n",
    "                            # with a refined shape,\n",
    "                            # that is, with certain edges and faces cleaned up\n",
    "                            print('Remove splitter')\n",
    "                            shape=solid.removeSplitter()\n",
    "\n",
    "                            print('Get volumes')\n",
    "                            shape_volume=shape.Volume\n",
    "\n",
    "                            # Work only on shapes with certain volume ratio\n",
    "                            # to the main assembly\n",
    "                            print('Individual solid shape volume: {:.1f} \\n(Object shape volume: {:.1f})'\\\n",
    "                                      .format(shape_volume,obj_volume))\n",
    "\n",
    "                            if shape_volume > 0.10 * obj_volume:\n",
    "\n",
    "                                print('Individual solid considered in the extraction, adressing solid...')\n",
    "                                try:\n",
    "                                    # Check for working only on valid shapes\n",
    "                                    print('Check validity...')\n",
    "                                    shape.sewShape()\n",
    "                                    shape.check()\n",
    "\n",
    "                                    # Retrive edges information\n",
    "                                    print('Edges...')\n",
    "                                    edges_retrieve(shape)\n",
    "\n",
    "                                    # Retrieve faces information\n",
    "                                    print('Faces...')\n",
    "                                    faces_retrieve(shape)\n",
    "\n",
    "                                    # Retrieve volumes and bounding box\n",
    "                                    print('Volumes...')\n",
    "                                    volumes_retrieve(shape)\n",
    "\n",
    "                                    # Retrieve holes:\n",
    "                                    print('Holes...')\n",
    "                                    holes=[]\n",
    "                                    holes_retrieve(shape)\n",
    "\n",
    "                                    # Generate optimal oriented box\n",
    "                                    # around object:\n",
    "                                    try:\n",
    "                                        print('Box...')\n",
    "                                        box_retrieve(shape)\n",
    "                                    except:\n",
    "                                        print('Error in box retrieval: skipped.')\n",
    "                                        variables_dict['boundbox_optimized_volume']=np.nan\n",
    "                                        variables_dict['boundbox_optimized_volume_ratio']=np.nan\n",
    "                                    print('Features extracted.')\n",
    "                                    # Create DataFrame of features for a single step file from the dictionnary\n",
    "                                    df_feature=pd.DataFrame.from_dict({step_file: variables_dict}).T\n",
    "                                    \n",
    "                                    # Register the information on file processed in the dataframe\n",
    "                                    path_list=os.path.normpath(step_file).split(os.path.sep)\n",
    "                                    print(path_list)\n",
    "                                    for i in range(len(path_list)):\n",
    "                                        df_feature['path_{}'.format(i)]=path_list[i]\n",
    "                                    df_feature['file_name']=os.path.basename(step_file)\n",
    "                                    df_feature['step_file']=step_file\n",
    "                                    display(df_feature)\n",
    "                                    df_features=pd.concat([df_features, df_feature], axis=0).reset_index(drop=True)\n",
    "                                except:\n",
    "                                    print('Error in shape check: current shape skipped.')\n",
    "                            else:\n",
    "                                print('Shape too small, is skipped.')\n",
    "                        except AttributeError:\n",
    "                            print('Issue with solid, is skipped.')\n",
    "\n",
    "                    FreeCAD.closeActiveTransaction()\n",
    "\n",
    "            # Save dataframe as .npz file\n",
    "            np.savez(step_path+'/step_data_{}_from_{}.npz'\\\n",
    "                     .format(batch+1, batches), features=df_features,\n",
    "                     names=df_features.columns)\n",
    "            print('npz file for this batch generated')\n",
    "        \n",
    "        except dummy_error:\n",
    "            print('Error in batch: current batch skipped.')\n",
    "            skipped_batch+=1\n",
    "\n",
    "print('Done')\n",
    "print('Number of batch skipped: ',skipped_batch)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
